version: '3.5'
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./init-scripts

services:
  voting-app:
    container_name: voting-app
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - '8080'
    ports:
      - '8080:8080'
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_URL=jdbc:postgresql://postgres:5432/voting
    depends_on:
      - postgres

  postgres:
    image: 'postgres:12.10'
    hostname: postgres
    container_name: postgres
    ports:
      - 5433:5432
    volumes:
      - db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voting