version: '3.5'
volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./config/init-scripts

services:
  voting-app:
    container_name: voting-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    environment:
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_URL=jdbc:postgresql://postgres:5432/voting
    depends_on:
      - postgres

  mail-sender:
    image: 'mailsender:latest'
    container_name: mail-sender
    hostname: mailservise
    ports:
      - 90:8081

  postgres:
    image: 'postgres:16.1-alpine'
    hostname: postgres
    container_name: postgres
    volumes:
      - db:/docker-entrypoint-initdb.d
      - /var/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: voting