#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

spring:
  jpa:
#    show-sql: true
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20

  # Jackson Serialization Issue Resolver

  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
    default-property-inclusion: non_null

  #    https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
  cache:
    cache-names: users, restaurants, result
    caffeine:
      spec: maximumSize=200,expireAfterAccess=3600s

  mvc:
    format:
      date: iso
      time: iso
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  aop:
    proxy-target-class: false

#  sql:
#    init:
#      mode: always
#  messages:
#    basename: app

  profiles:
    active: ru_date_format, postgres

logging:
  level:
    root: WARN
    ru.ustinov.voting: INFO
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.orm.jpa: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cache: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

sendMails:
 url: http://localhost:8081/mail

server:
  servlet:
    context-path: /voting

---
spring:
  config:
    activate:
      on-profile: postgres

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  sql:
#    init:
#      data-locations: classpath:data.sql
#      schema-locations: classpath:db/postgres_init.sql
#      mode: always
---
spring:
  config:
    activate:
      on-profile: heroku

  datasource:
    url: jdbc:postgresql://ec2-52-49-23-139.eu-west-1.compute.amazonaws.com:5432/dcfkcrs5bs4r4o
    username: hssojihqmfgoce
    password: ef9c251cb9aa03c0befb4c85e77bf41c09980b8b1c173ff87efb4e52ccea1c2d

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: false
        use_sql_comments: false

    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
      # ImMemory
    url: jdbc:h2:mem:voting
      #   tcp: jdbc:h2:tcp://localhost:9092/mem:voting
    h2.console.enabled: true

---
spring:
  config:
    activate:
      on-profile: ru_date_format
  mvc:
    format:
      date: dd.MM.yyyy



