#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

spring:
  jpa:
    show-sql: true
    open-in-view: false
    # https://stackoverflow.com/a/67678945/548473
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        # https://stackoverflow.com/questions/21257819/what-is-the-difference-between-hibernate-jdbc-fetch-size-and-hibernate-jdbc-batc
        jdbc.batch_size: 20

  # Jackson Serialization Issue Resolver

  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none
    default-property-inclusion: non_null

  #    https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#common-application-properties-cache
  cache:
    cache-names: users, restaurants, result
    caffeine:
      spec: maximumSize=200,expireAfterAccess=3600s

  mvc:
    format:
      date: iso
      time: iso
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  aop:
    proxy-target-class: false

  sql:
    init:
      mode: always
#  messages:
#    basename: app

  profiles:
    active: "h2"

logging:
  level:
    root: WARN
    ru.ustinov.voting: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.orm.jpa: DEBUG
    org.springframework.cache: DEBUG

server.servlet:
  encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly
    enabled: true # Enable http encoding support
    force: true

server:
  servlet:
    context-path: /api

---
spring:
  config:
    activate:
      on-profile: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/voting
    username: user
    password: password

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
      # ImMemory
    url: jdbc:h2:mem:voting
      #   tcp: jdbc:h2:tcp://localhost:9092/mem:voting
    h2.console.enabled: true



